name: b2b_partenership
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.5+15

environment:
  sdk: ^3.6.1


dependencies:
  audioplayers: ^6.5.1
  avatar_glow: ^3.0.1
  awesome_notifications: ^0.10.1
  cached_network_image: ^3.4.1
  carousel_slider: ^5.1.1
  connectivity_plus: ^7.0.0
  convex_bottom_bar: ^3.2.0
  dartz: ^0.10.1
  dio: ^5.9.0
  easy_loading_button: ^0.4.0
  equatable: ^2.0.7
  file_picker: ^10.3.6
  firebase_core: ^4.2.1
  firebase_messaging: ^16.0.4
  flutter:
    sdk: flutter
  flutter_cached_pdfview: ^0.4.3
  flutter_otp_text_field: ^1.5.1+1
  flutter_pannable_rating_bar: ^2.7.2+1
  flutter_rating_bar: ^4.0.1
  flutter_screenutil: ^5.9.3
  flutter_sound: ^9.28.0
  flutter_svg: ^2.2.2
  font_awesome_flutter: ^10.12.0
  gap: ^3.0.1
  get: ^4.7.2
  googleapis_auth: ^2.0.0
  http: ^1.6.0
  image_picker: ^1.2.1
  intl: ^0.20.2
  logger: ^2.6.2
  lottie: ^3.3.2
  lucide_icons_flutter: ^3.1.6
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  readmore: ^3.0.0
  record: ^6.1.2
  rename: ^3.1.0
  skeletonizer: ^2.1.0+1
  smooth_page_indicator: ^1.2.1
  timeago: ^3.7.1
  timezone: ^0.10.1
  upgrader: ^12.3.0
  url_launcher: ^6.3.2
  webview_flutter: ^4.13.0
  widget_zoom: ^0.0.4
  shimmer: ^3.0.0
  cupertino_icons: ^1.0.8
  device_preview: ^1.3.1
  flutter_quill: ^11.5.0

 


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/svgs/
    - assets/lottie/
    # - assets/fonts/Cairo-Regular.ttf

  fonts:
    - family: PlaypenSans
      fonts:
       - asset: assets/fonts/Playpen_Sans/PlaypenSans-ExtraBold.ttf
         weight: 800

       - asset: assets/fonts/Playpen_Sans/PlaypenSans-Bold.ttf
         weight: 700

       - asset: assets/fonts/Playpen_Sans/PlaypenSans-SemiBold.ttf
         weight: 600

       - asset: assets/fonts/Playpen_Sans/PlaypenSans-Medium.ttf
         weight: 500

       - asset: assets/fonts/Playpen_Sans/PlaypenSans-Regular.ttf
         weight: 400

       - asset: assets/fonts/Playpen_Sans/PlaypenSans-Light.ttf
         weight: 300

       - asset: assets/fonts/Playpen_Sans/PlaypenSans-ExtraLight.ttf
         weight: 200

       - asset: assets/fonts/Playpen_Sans/PlaypenSans-Thin.ttf
         weight: 100

    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Thin.ttf
          weight: 100

        - asset: assets/fonts/Roboto/Roboto-ExtraLight.ttf
          weight: 200

        - asset: assets/fonts/Roboto/Roboto-Light.ttf
          weight: 300

        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
          weight: 400

        - asset: assets/fonts/Roboto/Roboto-Medium.ttf
          weight: 500

        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
          weight: 700

        - asset: assets/fonts/Roboto/Roboto-ExtraBold.ttf
          weight: 800
     
    - family: Cairo
      fonts:
        # - asset: assets/fonts/Cairo/Cairo-Thin.ttf
        #   weight: 100

        - asset: assets/fonts/Cairo/Cairo-ExtraLight.ttf
          weight: 200

        - asset: assets/fonts/Cairo/Cairo-Light.ttf
          weight: 300

        - asset: assets/fonts/Cairo/Cairo-Regular.ttf
          weight: 400

        - asset: assets/fonts/Cairo/Cairo-Medium.ttf
          weight: 500

        - asset: assets/fonts/Cairo/Cairo-SemiBold.ttf
          weight: 600

        - asset: assets/fonts/Cairo/Cairo-Bold.ttf
          weight: 700

        - asset: assets/fonts/Cairo/Cairo-ExtraBold.ttf
          weight: 800
        
        - asset: assets/fonts/Cairo/Cairo-Black.ttf
          weight: 900